#!/bin/bash

RES="$(acpi 2>/dev/null)"
if [ -z "$RES" ]; then
  exit 1
fi

split_battery_stats() {
   IFS=$'\n' read -d "" -ra arr <<< "${1//$2/$'\n'}"
   printf '%s\n' "${arr[3]%%,}/${arr[4]%:*}"
}

case "${RES}" in
  *Discharging*)
      echo -n "▾"
      split_battery_stats "${RES}" " "
  ;;

  *Full*)
      echo -n "▴100%"

  ;;

  *)
      echo -n "▴"
      split_battery_stats "${RES}" " "

  ;;
esac
