---
- name: Copy script for external non-HiDPI monitor usage with XPS
  copy: src=dotcommon/.setup_external_monitor.sh dest=~/.setup_external_monitor.sh
  become: yes
  become_user: "{{ username }}"

- name: Install parallel utility to run shell tasks in parallel
  become: yes
  become_user: "{% if ansible_facts.os_family != 'Darwin' %}root{% else %}{{ username }}{% endif %}"
  package:
    name: parallel
    state: latest

- name: Copy ssh config
  template:
    src: dotcommon/sshconfig
    dest: "~/.ssh/config"
  become: yes
  become_user: "{{ username }}"
  tags:
    - sshconfig

- name: Install taskwarrior to be a task manager
  become: yes
  become_user: "{% if ansible_facts.os_family != 'Darwin' %}root{% else %}{{ username }}{% endif %}"
  package:
    name: task
    state: latest

- name: Install acpi to be able to show battery in console
  become: yes
  become_user: root
  package:
    name: acpi
    state: latest
  when:
    - ansible_facts.os_family != 'Darwin'

- name: Install FZF to have fuzzy search in console with preview
  become: yes
  become_user: "{% if ansible_facts.os_family != 'Darwin' %}root{% else %}{{ username }}{% endif %}"
  package:
    name: fzf
    state: latest

- import_tasks: sysctl.yml
  when:
    - ansible_facts.os_family != 'Darwin'

- name: Install battshow to be able to view battery status in console
  become: yes
  become_user: root
  copy:
    src: dotcommon/battshow
    dest: /usr/bin/battshow
    mode: u=rwx,g=rx,o=rx
  when:
    - ansible_facts.os_family != 'Darwin'

- name: Install 'shost' utility for fast search in SSH config
  become: yes
  become_user: root
  git:
    repo: https://github.com/sorrowless/tools.git
    dest: /opt/tools

- name: Place a symlink of 'shost' to PATH
  become: yes
  become_user: root
  file:
    src: /opt/tools/sshhost.py
    dest: /usr/local/bin/shost
    state: link

- name: Include pscircle tasks
  import_tasks: pscircle.yml
  when:
    - ansible_facts.os_family != 'Darwin'
