---
- name: Install git
  package:
    name: git
    state: latest

- name: Copy .gitconfig to user profile
  template: src=git/.gitconfig dest=~/.gitconfig

- name: Install tig
  package:
    name: tig
    state: latest
