---
#- import_tasks: backup.yml
- import_tasks: lsyncd.yml
- import_tasks: dotcommon.yml
  tags: 'dotcommon'
- import_tasks: git.yml
  tags: git
- import_tasks: rofi.yml
  tags: rofi
- import_tasks: screen.yml
- import_tasks: sysctl.yml
- import_tasks: tmux.yml
  tags: tmux
- import_tasks: vim.yml
  tags: vim
- import_tasks: vifm.yml
  tags: vifm

- import_tasks: zsh.yml
  when: zsh_enabled
  tags: 'zsh'

- import_tasks: media.yml
  tags: 'media'
- import_tasks: tools.yml
  tags: 'tools'
- import_tasks: packages.yml

# X11-related tasks
- import_tasks: x11/konsole.yml
  tags: ['x11', 'terminal', 'konsole']
- import_tasks: x11/sddm.yml
  tags: ['x11', 'sddm']
