---
#- import_tasks: backup.yml
- import_tasks: lsyncd.yml
- import_tasks: dotcommon.yml
  tags: 'dotcommon'
- import_tasks: git.yml
- import_tasks: rofi.yml
- import_tasks: screen.yml
- import_tasks: sysctl.yml
- import_tasks: tmux.yml
- import_tasks: vim.yml

- import_tasks: zsh.yml
  when: zsh_enabled
  tags: 'zsh'

- import_tasks: media.yml
  tags: 'media'
- import_tasks: tools.yml
  tags: 'tools'

# X11-related tasks
- import_tasks: x11/konsole.yml
  tags: ['x11', 'terminal', 'konsole']
- import_tasks: x11/sddm.yml
  tags: ['x11', 'sddm']
