---
#- import_tasks: backup.yml
- import_tasks: lsyncd.yml
- import_tasks: dotcommon.yml
  tags: 'dotcommon'
- import_tasks: git.yml
- import_tasks: rofi.yml
- import_tasks: screen.yml
- import_tasks: sddm.yml
  tags: 'sddm'
- import_tasks: sysctl.yml
- import_tasks: tmux.yml
- import_tasks: vim.yml
- import_tasks: zsh.yml
