---
- name: Install vifm
  package:
    name: vifm
    state: latest

    #- name: Install ueberzug
    #  become: yes
    #  become_user: "{{ ansible_user }}"
    #  aur:
    #    name: python-ueberzug

- name: Ensure vifm config directory
  file:
    state: directory
    path: "~/.config/vifm"
    mode: 0750
    owner: "{{ ansible_user }}"

- name: Copy vifm config to user home directory
  template:
    src: vifm/vifmrc
    dest: ~/.config/vifm/vifmrc
    mode: 0644
    owner: "{{ ansible_user }}"

- name: Ensure vifmimg script to work with ueberzug
  copy:
    src: "vifm/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
  with_items:
    - vifmimg
    - vifm-ueberzug
  become: yes
  become_user: root

- name: Ensure vifm zsh extensions for run with ueberzug
  copy:
    src: vifm/vifm.zsh
    dest: ~/.rc/vifm
    mode: 0644
    owner: "{{ ansible_user }}"
  when: zsh_enabled

- name: Ensure vifm devicons
  git:
    repo: 'https://github.com/sorrowless/vifm_devicons.git'
    dest: "~/.config/vifm/vifm_devicons"
    depth: 1

- name: Ensure local fonts directory
  file:
    state: directory
    path: "~/.local/share/fonts"
    mode: 0750
    owner: "{{ ansible_user }}"
  when: ansible_os_family != 'Darwin'


- name: Get Bitstream Vera Mono Hack font for vifm
  get_url:
    url: 'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/BitstreamVeraSansMono/Regular/complete/Bitstream%20Vera%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.ttf'
    dest: "~/.local/share/fonts/Bitstream Vera Sans Mono Nerd Font Complete Mono.ttf"
  register: font
  when: ansible_os_family != 'Darwin'

- name: Update cache
  command: fc-cache
  when: font.changed
  when: ansible_os_family != 'Darwin'
