---
- name: Install Neovim
  package:
    name: neovim
    state: latest

- name: Create directory for Neovim config
  file:
    path: ~/.config/nvim/
    state: directory

- name: Copy neovim config to user profile
  copy: src=nvim/init.vim dest=~/.config/nvim/
