---
- name: Install Vim
  package:
    name: vim
    state: latest

- name: Copy .vimrc to user profile
  copy: src=vim/.vimrc dest=~/.vimrc

- name: Install needed plugins
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: ~/.vim/bundle/Vundle.vim

    #- name: Activate needed plugins
    #  shell: vim +PluginInstall +qall
