---
- name: Install ZSH
  package:
    name: zsh
    state: latest

- name: Check user existance and create if does not exists
  user:
    group: "{{ ansible_user }}"
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  when: ansible_os_family != 'Darwin'

- name: Ensure zsh rc directory
  file:
    state: directory
    path: ~/.rc

- name: Copy .zshrc to user profile
  copy: src=zsh/.zshrc dest=~/.zshrc

- name: Copy keyboard-related zsh configuration
  copy: src=zsh/rc/zsh-keyboard dest=~/.rc/

- name: Copy alias zsh configuration
  copy: src=zsh/rc/zsh-aliases dest=~/.rc/

- name: Copy options and exports zsh configuration
  copy: src=zsh/rc/zsh-options dest=~/.rc/

- name: Copy zsh functions
  copy: src=zsh/rc/zsh-functions dest=~/.rc/

- name: Copy zsh configuration for external tools
  copy: src=zsh/rc/zsh-tools dest=~/.rc/

- name: Copy zsh completion configuration
  copy: src=zsh/rc/zsh-completion dest=~/.rc/
