---
- name: Install SDDM
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - sddm
    - "sddm-kcm"

- name: Checkout needed theme
  git:
    repo: "https://github.com/sorrowless/sddm-theme-{{ login_theme }}.git"
    dest: "/usr/share/sddm/themes/{{ login_theme }}"

- name: Ensure SDDM config file
  template:
    src: sddm/sddm.conf
    dest: /etc/sddm.conf
